name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    env:
      TF_IN_AUTOMATION: true
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} # Defined inside Terraform Cloud
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Defined inside Terraform Cloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.3
          terraform_wrapper: True
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }} # Defined inside Terraform Cloud
      - name: Terraform Init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate -no-color   
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
            context: ./src
            push: true
            tags: aws_ecr_repository.ecr.repository_url>:latest
        env:
            AWS_REGION: var.region
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
            registry: aws_ecr_repository.ecr.repository_url
      - name: Push Docker Image to ECR
        run: |
            docker tag aws_ecr_repository.ecr.repository_url:latest ${{ steps.login-ecr.outputs.registry }}/aws_ecr_repository.ecr.repository_url:latest
            docker push ${{ steps.login-ecr.outputs.registry }}/aws_ecr_repository.ecr.repository_url:latest